=== NIEM/MPD-Spec/mpd-catalog-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>

<schema
    attributeFormDefault="qualified"
    elementFormDefault="qualified"
    targetNamespace="http://reference.niem.gov/niem/resource/mpd/catalog/1.0/"
    xmlns="http://www.w3.org/2001/XMLSchema"
    xmlns:ca="http://reference.niem.gov/niem/resource/mpd/catalog/1.0/"
    version="1.0">
 
    <annotation>
	<documentation>
	    Model Package Description (MPD) Catalog;
 	    XML document element = Catalog;
	    This schema defines the catalog.xml artifact 
	    for Model Package Descriptions (MPD) in NIEM.
	    MPDs include:
		NIEM releases, core updates, domain updates, 
		NIEM Information Exchange Package Documentation (IEPD), 
		and NIEM Enterprise Information Exchange Models (EIEM). 

	    NOTE:  The purpose of this schema is to define/declare metadata 
	    for NIEM MPDs to search, discover, and process MPDs efficiently. 
	    Instances of this schema are NOT NIEM data exchanges.  For 
	    this reason this schema is NOT NIEM conforming, even though 
	    type definitions and element/attribute declarations generally 
	    conform to NIEM NDR naming rules.  
	</documentation>
    </annotation>

    <element name="Catalog" type="ca:CatalogType"/> <!-- Root element -->

<!-- Artifacts and structures =========================================== -->

    <complexType name="CatalogType">
        <sequence>
	    <element ref="ca:Artifact" minOccurs="1" maxOccurs="unbounded"/>
	    <element ref="ca:Metadata" minOccurs="1" maxOccurs="1"/>
        </sequence>
        <attribute	ref="ca:mpdURI"		use="required"/>
	<attribute	ref="ca:mpdClassCode"	use="required"/>
        <attribute	ref="ca:mpdName"	use="required"/>
        <attribute	ref="ca:mpdVersionID"	use="required"/>
        <attribute	ref="ca:descriptionText" use="optional"/>
    </complexType>

    <element name="Artifact" abstract="true"/>

    <element name="FileSet" type="ca:FileSetType" substitutionGroup="ca:Artifact"/>

    <complexType name="FileSetType">
	<sequence>
	    <element ref="ca:File" minOccurs="0" maxOccurs="unbounded"/>
	</sequence>
	<attribute	ref="ca:id"		    	use="required"/>
	<attribute	ref="ca:externalURI"	    	use="optional"/>
	<attribute	ref="ca:natureURI"	    	use="required"/>
	<attribute	ref="ca:purposeURI"	    	use="required"/>
	<attribute	ref="ca:descriptionText"    	use="optional"/>
	<attribute 	ref="ca:files" 			use="optional"/>
    </complexType>

    <element name="Folder" type="ca:FolderType" substitutionGroup="ca:Artifact"/>

    <complexType name="FolderType">
	<attribute	ref="ca:id"			use="optional"/>
	<attribute	ref="ca:relativePathName"	use="required"/>
	<attribute	ref="ca:descriptionText"	use="optional"/>
    </complexType>

    <element name="File" type="ca:FileType" substitutionGroup="ca:Artifact"/>

    <complexType name="FileType">
	<attribute	ref="ca:id"		    	use="required"/>
	<attribute	ref="ca:externalURI"	    	use="optional"/>
	<attribute	ref="ca:relativePathName"   	use="required"/>
	<attribute	ref="ca:natureURI"	    	use="required"/>
	<attribute	ref="ca:purposeURI"	    	use="required"/>
	<attribute	ref="ca:descriptionText"    	use="optional"/>
    </complexType>

<!-- Metadata =========================================================== -->

    <element name="Metadata" type="ca:MetadataType"/>

    <complexType name="MetadataType">
	<sequence>
	    <element ref="ca:SecurityMarkingText" minOccurs="1" maxOccurs="1"/>
	    <element ref="ca:CreationDate"	minOccurs="1" maxOccurs="1"/>
	    <element ref="ca:LastRevisionDate"	minOccurs="0" maxOccurs="1"/>
	    <element ref="ca:NextRevisionDate"	minOccurs="0" maxOccurs="1"/>
	    <element ref="ca:StatusText"	minOccurs="0" maxOccurs="1"/>
	    <element ref="ca:Relationship"	minOccurs="0" maxOccurs="unbounded"/>
	    <element ref="ca:KeywordText" minOccurs="1" maxOccurs="unbounded"/>
	    <element ref="ca:DomainText"  minOccurs="1" maxOccurs="unbounded"/>
	    <element ref="ca:PurposeText" minOccurs="0" maxOccurs="unbounded"/>
	    <element ref="ca:ExchangePatternText" minOccurs="0" maxOccurs="unbounded"/>
	    <element ref="ca:ExchangePartnerName" minOccurs="0" maxOccurs="unbounded"/>
	    <element ref="ca:AuthoritativeSource" minOccurs="1" maxOccurs="1"/>
	</sequence>
    </complexType>

    <element name="AuthoritativeSource" type="ca:AuthoritativeSourceType"/>

    <complexType name="AuthoritativeSourceType">
	<sequence>
	    <element ref="ca:ASName"	    	minOccurs="1"   maxOccurs="1"/>
	    <element ref="ca:ASAddressText"   minOccurs="0"   maxOccurs="1"/>
	    <element ref="ca:ASWebSiteURL"	minOccurs="0"   maxOccurs="1"/>
	    <element ref="ca:POC"	minOccurs="1"   maxOccurs="unbounded"/>
	</sequence>
    </complexType>

    <element name="POC" type="ca:POCType"/>

    <complexType name="POCType">
	<sequence>
	   <element ref="ca:POCName"	minOccurs="1"  maxOccurs="1"/>
	   <element ref="ca:POCEmail" minOccurs="1"  maxOccurs="unbounded"/>
	   <element ref="ca:POCTelephone" minOccurs="1"   maxOccurs="unbounded"/>
	</sequence>
    </complexType>

    <element name="SecurityMarkingText"	type="string"	default="unclassified"/>
    <element name="CreationDate"		type="date"/>
    <element name="LastRevisionDate"	type="date"/>
    <element name="NextRevisionDate"	type="date"/>
    <element name="StatusText"	    	type="string"/>
    <element name="Relationship"		type="ca:RelationshipType"/>
    <element name="KeywordText"		type="string"/>
    <element name="DomainText"	    	type="string"/>
    <element name="PurposeText"	    	type="string"/>

    <element name="ExchangePatternText" 	type="string"/>
    <element name="ExchangePartnerName" 	type="string"/>

    <element name="ASName"			type="string"/>
    <element name="ASAddressText"	    	type="string"/>
    <element name="ASWebSiteURL" 		type="anyURI"/>
    <element name="POCName"	    		type="string"/>
    <element name="POCEmail"			type="string"/>
    <element name="POCTelephone"		type="string"/>

    <complexType name="RelationshipType">
	<attribute ref="ca:relationshipCode"    use="required"/>
	<attribute ref="ca:resourceURI"	    use="required"/>
	<attribute ref="ca:descriptionText"     use="optional"/>
    </complexType>

<!-- Primitives ========================================================= -->

    <attribute name="id"			type="ID"/>
    <attribute name="mpdURI"			type="ca:URISimpleType"/>
    <attribute name="mpdClassCode"		type="ca:MPDClassCodeSimpleType"/>
    <attribute name="mpdName"			type="string"/>
    <attribute name="mpdVersionID"		type="ca:MPDVersionIDSimpleType"/>
    <attribute name="externalURI"		type="ca:URISimpleType"/>
    <attribute name="relativePathName"	type="string"/>
    <attribute name="natureURI"		type="ca:URISimpleType"/>
    <attribute name="purposeURI"		type="ca:URISimpleType"/>
    <attribute name="descriptionText"	type="string"/>
    <attribute name="files"			type="IDREFS"/>
    <attribute name="resourceURI"		type="ca:URISimpleType"/>
    <attribute name="relationshipCode" type="ca:RelationshipCodeSimpleType"/>

    <simpleType name="MPDClassCodeSimpleType">
	<restriction base="token">
	    <enumeration value="release"/>
	    <enumeration value="core-update"/>
	    <enumeration value="domain-update"/>
	    <enumeration value="iepd"/>
	    <enumeration value="eiem"/>
	</restriction>
    </simpleType>

    <simpleType name="RelationshipCodeSimpleType">
	<restriction base="token">
	    <enumeration value="version_of"/>
	    <enumeration value="specializes"/>
	    <enumeration value="generalizes"/>
	    <enumeration value="supersedes"/>
	    <enumeration value="deprecates"/>
	    <enumeration value="adapts"/>
	    <enumeration value="updates"/>
	    <enumeration value="conforms_to"/>
	</restriction>
    </simpleType>

    <simpleType name="MPDVersionIDSimpleType">
        <restriction base="token">
	    <pattern value="[0-9]+(\.[0-9]+)*((alpha|beta|rc|rev)[0-9]+)?"/>
	    <minLength value="1"/>
        </restriction>
    </simpleType>

    <simpleType name="URISimpleType">
        <union memberTypes="anyURI ca:SafeCurieSimpleType"/>
    </simpleType>

    <simpleType name="SafeCurieSimpleType">
        <restriction base="string">
            <pattern value="\[(([\i-[:]][\c-[:]]*)?:)?.+\]"/>
            <minLength value="3"/>
        </restriction>
    </simpleType> 

</schema>

=== NIEM/MPD-Spec/mpd-catalog-example/mpd-catalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="./mpd-catalog.xsl"?>

<!-- This IEPD catalog instance is for MPD Specification v1.1. 
It is a fictitious and abbreviated IEPD (NOT necessarily complete). 
However, it illustrates use of various options in mpd-catalog-1.0.xsd; 
including reuse of File elements with IDREFS in the "files" attribute, 
use of both full URIs and safe CURIEs, full, Folders, various metadata, 
references to external related MPDs and artifacts, etc.  -->

<ca:Catalog

   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xmlns:ca="http://reference.niem.gov/niem/resource/mpd/catalog/1.0/"
   xmlns:p="http://reference.niem.gov/niem/resource/mpd/lexicon/1.1/purpose#"
   xmlns:n="http://reference.niem.gov/niem/resource/mpd/lexicon/1.1/nature#"
   xmlns:yy="http://my.iepd.program.org/aaa/"
   xmlns:zz="http://zoom.com/services/plan-order/"
  
   xsi:schemaLocation="http://reference.niem.gov/niem/resource/mpd/catalog/
   1.0/mpd-catalog-1.0.xsd"

    ca:mpdURI="http://myiepd.org/p-ord/1.5/"
    ca:mpdClassCode="iepd"
    ca:mpdName="Planning_Order"
    ca:mpdVersionID="1.5"
    ca:descriptionText="A Planning Order notifies subordinate agencies 
    			to initiate planning for contingency operations." >

    <ca:FileSet ca:id="base0"
	ca:externalURI="[yy:plnord/4.6/#b0]"
	ca:natureURI="[n:schema-set]"
	ca:purposeURI="[p:base-schema-set]"
	ca:descriptionText="Base schema set for IEPD Planning Order">

	<ca:File ca:id="w1"
	    ca:relativePathName="./subset/wantlist1.xml"
	    ca:natureURI="[n:niem-wantlist]"
	    ca:purposeURI="[p:set-member]"
	    ca:descriptionText="my wantlist 1"/>

	<ca:File ca:id="s1"
	    ca:relativePathName="./subset/niem/niem-core/2.0/niem-core.xsd"
	    ca:natureURI="[n:niem-subset-schema]"
	    ca:purposeURI="[p:set-member]"
	    ca:descriptionText="niem core subset"/>

	<ca:File ca:id="e1"
	    ca:relativePathName="./extension/ext1.xsd"
	    ca:natureURI="[n:niem-extension-schema]"
	    ca:purposeURI="[p:set-member]"
	    ca:descriptionText="Plan Order extension schema 1"/>

   	<ca:File ca:id="e2"
	    ca:relativePathName="./extension/ext2.xsd"
	    ca:natureURI="[n:niem-extension-schema]"
	    ca:purposeURI="[p:set-member]"
	    ca:descriptionText="Plan Order extension schema 2"/>

    	<ca:File ca:id="e3"
	    ca:externalURI="[zz:po8/1.0/#exten1]" 
	    ca:relativePathName="./extension/ext3.xsd"
	    ca:natureURI="[n:niem-extension-schema]"
	    ca:purposeURI="[p:set-member]"
	    ca:descriptionText="Plan Order extension schema 3"/>

	<ca:File ca:id="r1"
	    ca:relativePathName="./exchange/myiepd.xsd"
	    ca:natureURI="[n:niem-exchange-schema]"
	    ca:purposeURI="[p:set-member]"
	    ca:descriptionText="exchange schema for Plan Order"/>

    </ca:FileSet>

    <ca:File ca:id="c0"
	ca:relativePathName="./mpd-catalog.xml"
	ca:natureURI="[n:niem-mpd-catalog]"
	ca:purposeURI="[p:catalog]"
	ca:descriptionText="MPD Catalog: identifies artifacts in Plan Order"/>

    <ca:File ca:id="cl"
	ca:relativePathName="./changelog.txt"
	ca:natureURI="[n:text]" 
	ca:purposeURI="[p:changelog]"
	ca:descriptionText="History of changes to Planning Order"/>

    <ca:File ca:id="cs0"
	ca:relativePathName="./mpd-catalog.xsl"
	ca:natureURI="[n:xslt]"
	ca:purposeURI="[p:display]"
	ca:descriptionText="stylesheet displays mpd-catalog index + metadata"/>

    <ca:FileSet ca:id="s99"
	ca:externalURI="[zz:po6/2.2/#z55]"
	ca:natureURI="[n:file-set]"
	ca:purposeURI="[p:documentation]"
	ca:descriptionText="Additional documentation">

	<ca:File ca:id="h1"
	    ca:relativePathName="./doc/1.htm"
	    ca:natureURI="[n:html]"
	    ca:purposeURI="[p:set-member]"
	    ca:descriptionText="supplemental doc 1"/>

	<ca:File ca:id="h2"
	    ca:relativePathName="./doc/index.htm"
	    ca:natureURI="[n:html]"
	    ca:purposeURI="[p:set-member]"
	    ca:descriptionText="supplemental doc 2"/>

	<ca:File ca:id="h3"
	    ca:relativePathName="./doc/3.htm"
	    ca:natureURI="[n:html]"
	    ca:purposeURI="[p:subordinate-set-member]"
	    ca:descriptionText="supplemental doc 3"/>

	<ca:File ca:id="h4"
	    ca:relativePathName="./doc/4.htm"
	    ca:natureURI="[n:html]"
	    ca:purposeURI="[p:subordinate-set-member]"
	    ca:descriptionText="supplemental doc 4"/>

	<ca:File ca:id="g5"
	    ca:relativePathName="./doc/5.gif"
	    ca:natureURI="[n:gif]"
	    ca:purposeURI="[p:subordinate-set-member]"
	    ca:descriptionText="supplemental doc 5"/>

    </ca:FileSet>

    <ca:File ca:id="br0"
	ca:externalURI="[yy:plnord/4.6/#ru1]"
	ca:relativePathName="./business-rules/rules0.sch"
	ca:natureURI="[n:schematron]" 
	ca:purposeURI="[p:business-rules]"
	ca:descriptionText="Additional constraints on Plan Order instances"/>

    <ca:File ca:id="t4"
	ca:relativePathName="./test/test-summary.docx"
	ca:natureURI="[n:doc]"
	ca:purposeURI="[p:test-report]"
	ca:descriptionText="Test data and summary report for Plan Order"/>

    <ca:File ca:id="md0"
	ca:relativePathName="./master-document.docx"
	ca:natureURI="[n:doc]" 
	ca:purposeURI="[p:master-document]"
	ca:descriptionText="Readme file for implementing Plan Order"/>

    <ca:FileSet ca:id="css1"
	ca:natureURI="[n:schema-set]"
	ca:purposeURI="[p:constraint-schema-set]"
	ca:descriptionText="constraint schema set 1"
	ca:files="e1  e2  r1  cs88" />

    <ca:FileSet ca:id="css2"
	ca:natureURI="[n:schema-set]"
	ca:purposeURI="[p:constraint-schema-set]"
	ca:descriptionText="constraint schema set 2"
	ca:files="cs91  e2  r1  s1" />

    <ca:File ca:id="cs88"
	ca:relativePathName="./constraint/nc-cs88.xsd"
	ca:natureURI="http://reference.niem.gov/niem/resource/mpd/lexicon/1.1/nature#niem-constraint-schema" 
	ca:purposeURI="[p:set-member]"
	ca:descriptionText="Constrained niem-core 2.0"/>

    <ca:File ca:id="cs91"
	ca:relativePathName="./constraint/ext1-cs91.xsd"
	ca:natureURI="http://reference.niem.gov/niem/resource/mpd/lexicon/1.1/nature#niem-constraint-schema" 
	ca:purposeURI="[p:set-member]"
	ca:descriptionText="Constrained extension 1"/>

<!-- Folders (directories) -->

    <ca:Folder ca:id="f0"
	ca:relativePathName="./"
	ca:descriptionText="ROOT"/>

    <ca:Folder ca:id="f1"
	ca:relativePathName="./subset/"
	ca:descriptionText="SUBSET"/>

    <ca:Folder ca:id="nc2"
	ca:relativePathName="./subset/niem/niem-core/2.0/"
	ca:descriptionText="NIEM CORE 2.0"/>

    <ca:Folder ca:id="f2"
	ca:relativePathName="./extension/"
	ca:descriptionText="EXTENSION"/>

    <ca:Folder ca:id="f3"
	ca:relativePathName="./exchange/"
	ca:descriptionText="EXCHANGE"/>

    <ca:Folder ca:id="f4"
	ca:relativePathName="./library/"
	ca:descriptionText="LIBRARY"/>

    <ca:Folder ca:id="f5"
	ca:relativePathName="./documentation/"
	ca:descriptionText="DOCUMENTATION"/>

    <ca:Folder ca:id="f6"
	ca:relativePathName="./xml-samples/"
	ca:descriptionText="SAMPLE INSTANCES"/>

    <ca:Folder ca:id="f7"
	ca:relativePathName="./doc/"
	ca:descriptionText="SUPPLEMENTAL DOCUMENTATION"/>

    <ca:Folder ca:id="f8"
	ca:relativePathName="./constraint/"
	ca:descriptionText="CONSTRAINT SCHEMAS"/>

    <ca:Folder ca:id="f9"
	ca:relativePathName="./business-rules/"
	ca:descriptionText="BUSINESS RULES"/>

    <ca:Metadata>

	<ca:SecurityMarkingText>Unclassified/public</ca:SecurityMarkingText>
	<ca:CreationDate>2009-02-16</ca:CreationDate>
	<ca:LastRevisionDate>2010-04-20</ca:LastRevisionDate>
	<ca:StatusText>
	    implemented and operational in 25 of 50 states since 2009
	</ca:StatusText>
	
	<ca:Relationship ca:relationshipCode="adapts"
			 ca:resourceURI="[zz:po6/2.2/]"
			 ca:descriptionText="reuses one documentation set artifact" />
	<ca:Relationship
			 ca:relationshipCode="adapts"
			 ca:resourceURI="[zz:po8/1.0/]"
			 ca:descriptionText="uses adapted extension schema" />

	<ca:KeywordText>program plan</ca:KeywordText>
	<ca:KeywordText>contingency</ca:KeywordText>
	<ca:KeywordText>planning</ca:KeywordText>

	<ca:DomainText>Logistics</ca:DomainText>
	<ca:DomainText>Emergency Management</ca:DomainText>
	<ca:PurposeText>intended to initiate execution of planning cycles</ca:PurposeText>
	<ca:ExchangePatternText>query/response</ca:ExchangePatternText>
	<ca:ExchangePartnerName>FEMA</ca:ExchangePartnerName>
	<ca:ExchangePartnerName>NASCIO</ca:ExchangePartnerName>
	<ca:ExchangePartnerName>82d Abn Div</ca:ExchangePartnerName>

	<ca:AuthoritativeSource>
	    <ca:ASName>FEMA</ca:ASName>
	    <ca:ASAddressText>30 Dupont Cir, Wash DC, 12345,USA</ca:ASAddressText>
	    <ca:ASWebSiteURL>http://www.fema.gov</ca:ASWebSiteURL>
	    <ca:POC>
		<ca:POCName>John Smith</ca:POCName>   
		<ca:POCEmail>john.smith@fema.gov</ca:POCEmail>
		<ca:POCTelephone>202-333-1234</ca:POCTelephone>
	    </ca:POC>
	    <ca:POC>
		<ca:POCName>FEMA, Office of the Chief Administrator</ca:POCName>
		<ca:POCEmail>OCA@fema.gov</ca:POCEmail>
		<ca:POCTelephone>888-333-5678</ca:POCTelephone>
	    </ca:POC>
	</ca:AuthoritativeSource>

    </ca:Metadata>

</ca:Catalog>
